#!/bin/bash

set -e

get_gpu() {
    gpu=$(prime-select query)
    if [ $gpu == "intel" ]
    then
        echo "amd"
    else
        echo "nvidia"
    fi
}


i3status() {
  while :
  do
    read line
    block="{\"full_text\":\"$(get_gpu)\"}"
    echo "${line/\[\{/\[$block,\{}"|| exit 1
  done
}

i3status
